version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 3
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - app-network

  hellorabbitmq:
    build: ./HelloRabbitMq
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RabbitMq__HostName: rabbitmq
      RabbitMq__UserName: user
      RabbitMq__Password: password
    networks:
      - app-network

  receiver:
    build: ./Receiver
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RabbitMq__HostName: rabbitmq
      RabbitMq__UserName: user
      RabbitMq__Password: password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge